apiVersion: autoscaling/v2beta1
kind: Deployment
metadata:
  name: podinfo
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  replicas: 1
  strategy:
    type: Recreate
#  minReplicas: 1
#  maxReplicas: 4
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
      # scale up if usage is above
      # 99% of the requested CPU (10m)
#      targetAverageUtilization: 99
